
```{r}
library(cheeseTrap)
```


```{r}
```

```{r}

body_weight$mouse_number <- seq_along(body_weight[["Body_Weight_1"]])

# Testing the logic outside of the function
body_weight[["Body_Weight_2"]] <- as.numeric(body_weight[["Body_Weight_2"]])
body_weight[["Body_Weight_1"]] <- as.numeric(body_weight[["Body_Weight_1"]])

# Filter to remove NAs in the specified columns
body_weight <- dplyr::filter(body_weight, !is.na(body_weight[["Body_Weight_2"]]) & !is.na(body_weight[["Body_Weight_1"]]))
body_weight


# Numerically identify outliers for the y_var (Body_Weight_1)
#mean_y <- mean(body_weight[["Body_Weight_1"]], na.rm = TRUE)
#sd_y <- sd(body_weight[["Body_Weight_1"]], na.rm = TRUE)

# Identify outliers (+- 2.5 std from mean)
#outliers <- body_weight[abs(body_weight[["Body_Weight_1"]] - mean_y) > 2.5 * sd_y, ]
# Create a new variable to represent the row numbers for x-axis

lineplot <- ggplot2::ggplot(body_weight, ggplot2::aes(x = row_number, y = Body_Weight_1)) +
  ggplot2::geom_point() +
  ggplot2::labs(title = "Boxplot of Body Weight 1") +  # Correcting the title to reflect the boxplot
  ggplot2::theme_minimal()

# Interactive plot using Plotly
interactive_plot2 <- plotly::ggplotly(lineplot)
interactive_plot2  # Display the interactive plot


# Print the interactive plot
print(interactive_plot2)
```



















```{r}
outlier_detector(data=body_weight, y_var="Body_Weight_1")
```

```{r}
join_comparison(df1 = birth, df2 = body_weight, join_by = "ID")
```
```{r}

# Example
typo_flagger(birth, "Treatment")
```

```{r}
non_numeric_rows <- data_formatter(body_weight, 
                                         c("Body_Weight_1", "Body_Weight_2", "Body_Weight_3"))

```

